### ISSUE TITLE
"Uncaught TypeError: Cannot read property 'refs' of undefined" in Chrome

### ISSUE THREAD

**Issue by UnkrautFee** [jneilliii/Octoprint-STLViewer#19]
OctoPrint: 
Version 1.3.2 (master branch)

The following error occurs when selecting a file:

Uncaught TypeError: Cannot read property 'refs' of undefined
    at stlviewerViewModel.self.loadModel (packed_plugins.js?0d5f6395:108)
    at HTMLSelectElement.<anonymous> (packed_libs.js?8f75e9e5:10840)
    at HTMLSelectElement.dispatch (packed_libs.js?8f75e9e5:4737)
    at HTMLSelectElement.elemData.handle (packed_libs.js?8f75e9e5:4549)

![stlviewererrormessage](https://cloud.githubusercontent.com/assets/23253952/25484521/a1d0642e-2b5a-11e7-89e5-71e913f7df7f.PNG)

Debugger shows that "model" is undefined.

![stlviewererrorcode](https://cloud.githubusercontent.com/assets/23253952/25484599/ea526800-2b5a-11e7-827a-5470870a3242.PNG)

But this only occurs when using Google Chrome. In FireFox everything is fine and the STL Viewer works perfectly.

**Comment by jneilliii** [comment]
Issue should be fixed with latest 0.4.1 version.

**Comment by ondrajz** [comment]
This still happens to me in Chrome with version 0.4.1. Does not happen in Firefox.

![screenshot_2017-09-26_21-22-38](https://user-images.githubusercontent.com/1229233/30879820-daea04ae-a300-11e7-9d7b-f950543c0ead.png)

**Comment by jneilliii** [comment]
Does that happen when you select a file or switch to the tab? I haven't really encountered the error myself in chrome, but I also don't use folders.

**Comment by ondrajz** [comment]
When I select some model.
